dist: trusty

sudo: false

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

matrix:
  include:
    - os: linux
      compiler: clang
      env:
        build_type=release
        options=""
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++"
        
    - os: linux
      compiler: gcc
      env:
        build_type=release
        options=""
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
    - eval "${MATRIX_EVAL}"
    
script:
  - cmake -DLIB_INSTALL_DIR=/usr/lib .
  - cmake --build . -- -j2
